'use server';
/**
 * @fileOverview A flow to generate detailed AI prompts from a simple idea.
 *
 * - generatePrompt - A function that takes an idea and a goal to generate a detailed prompt.
 * - GeneratePromptInput - The input type for the generatePrompt function.
 * - GeneratePromptOutput - The return type for the generatePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePromptInputSchema = z.object({
  idea: z.string().describe('The basic idea or concept for the prompt.'),
  goal: z
    .enum([
      'Image Generation',
      'Creative Writing',
      'Code Snippet',
      'Email Draft',
      'Marketing Copy',
      'General Question',
    ])
    .describe('The primary goal or category for the generated prompt.'),
});
export type GeneratePromptInput = z.infer<typeof GeneratePromptInputSchema>;

const GeneratePromptOutputSchema = z.object({
  generatedPrompt: z.string().describe('The detailed, well-structured prompt generated by the AI.'),
});
export type GeneratePromptOutput = z.infer<typeof GeneratePromptOutputSchema>;

export async function generatePrompt(input: GeneratePromptInput): Promise<GeneratePromptOutput> {
  return generatePromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'promptGeneratorPrompt',
  input: {schema: GeneratePromptInputSchema},
  output: {schema: GeneratePromptOutputSchema},
  prompt: `You are a prompt engineering expert. Your task is to take a user's simple idea and expand it into a detailed, effective, and well-structured prompt that is optimized for an AI model.

The user's goal for this prompt is: **{{{goal}}}**.

Consider the best practices for this goal. For example:
- For **Image Generation**, include details about subject, style, composition, lighting, color, and mood. Use descriptive keywords.
- For **Creative Writing**, establish context, characters, setting, tone, plot points, and desired output format (e.g., a short story, a poem).
- For **Code Snippets**, specify the programming language, required libraries, function signature, logic, inputs, and expected output.
- For **Email Drafts**, include the purpose, recipient, sender's role, key information to include, desired tone (e.g., formal, friendly), and a call to action.
- For **Marketing Copy**, define the product/service, target audience, key benefits, desired tone, and the call to action.
- For a **General Question**, rephrase it to be specific, unambiguous, and provide necessary context to get a comprehensive answer.

User's basic idea:
"{{{idea}}}"

Now, generate a single, detailed, and enhanced prompt based on this idea and goal. The prompt should be ready to be copied and pasted into another AI tool. Do not add any conversational text or explanations around the prompt itself.
`,
});

const generatePromptFlow = ai.defineFlow(
  {
    name: 'generatePromptFlow',
    inputSchema: GeneratePromptInputSchema,
    outputSchema: GeneratePromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
