'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/compose-email.ts';
import '@/ai/flows/generate-image.ts';
import '@/ai/flows/summarize-text.ts';
import '@/ai/flows/generate-avatar.ts';
import '@/ai/flows/caption-image.ts';
import '@/ai/flows/check-grammar.ts';
import '@/ai/flows/generate-code.ts';
import '@/ai/flows/generate-video.ts';
import '@/ai/flows/remove-background.ts';
import '@/ai/flows/text-to-speech.ts';
import '@/ai/flows/generate-chart.ts';
import '@/ai/flows/translator.ts';
import '@/ai/flows/sentiment-analyzer.ts';
import '@/ai/flows/tone-changer.ts';
import '@/ai/flows/quiz-generator.ts';
import '@/ai/flows/email-reply-generator.ts';
import '@/ai/flows/flashcard-generator.ts';
import '@/ai/flows/edit-image.ts';
import '@/ai/flows/social-content-generator.ts';
import '@/ai/flows/humanizer.ts';
import '@/ai/flows/youtube-transcript.ts';
import '@/ai/flows/story-writer.ts';
import '@/ai/flows/non-fiction-writer.ts';
import '@/ai/flows/talking-photo.ts';
import '@/ai/flows/image-to-cartoon.ts';
import '@/ai/flows/image-to-animation.ts';
import '@/ai/flows/lyrics-generator.ts';
import '@/ai/flows/enhance-image.ts';
import '@/ai/flows/document-analyzer.ts';
import '@/ai/flows/chatbot.ts';
import '@/ai/flows/generate-linkedin-headshot.ts';
